# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WarrantyWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Google/SignIn'
pod 'GoogleSignIn'
pod 'MRCountryPicker','~> 0.0.7'
  # Pods for WarrantyWallet

  target 'WarrantyWalletTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'MRCountryPicker', '~> 0.0.7'
  end


end
